- hosts: all
  become: yes
  tasks:
  - name: Uninstall old versions of Docker
    yum:
      state: absent
      name:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine

  - name: Install required packages
    yum:
      state: present
      name: 
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

  - name: install docker repository
    command:  yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install docker
    yum:
      state: latest
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io


  - name: Install docker compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.25.4/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
      dest: /usr/local/bin/docker-compose
      mode: 0755

  
  - name: Ensure Docker is started and enabled at boot
    service:
      name: docker
      state: started
      enabled: true

  - name: Add user vangrant in group docker
    user:
      name: vagrant
     group: docker
          
